# 日志分析系统的常见故障模式
known_fault_patterns = {
    "数据库相关故障": [
        "Database connection failed",
        "Database timeout",
        "Query execution failed",
        "Deadlock detected",
        "Transaction rollback",
        "Connection pool exhausted",
        "Invalid SQL syntax",
        "Database corruption"
    ],
    "网络相关故障": [
        "Connection refused",
        "Connection timeout",
        "DNS resolution failed",
        "SSL handshake error",
        "Network unreachable",
        "High latency detected",
        "Packet loss detected"
    ],
    "认证授权故障": ["Invalid credentials",
                     "Authentication failed",
                     "Token expired",
                     "Permission denied",
                     "Rate limit exceeded",
                     "IP blocked",
                     "Invalid API key"],
    "资源相关故障": [
        "Out of memory",
        "Disk space exhausted",
        "CPU overload",
        "File descriptor limit reached",
        "Thread pool exhausted"
    ],
    "服务依赖故障": ["Service unavailable",
                     "Dependency service timeout",
                     "Circuit breaker triggered",
                     "Health check failed",
                     "Version mismatch"],
    "数据格式/业务逻辑故障": ["Invalid input format",
                              "Data validation failed",
                              "Missing required field",
                              "Duplicate entry",
                              "Business rule violation"],
    "文件/IO故障": ["File not found",
                    "Permission denied",
                    "Disk I/O error",
                    "File system full",
                    "File write failed"],
    "配置相关故障": ["Invalid configuration",
                     "Missing configuration",
                     "Environment variable not set",
                     "Certificate expired"],
}
